### ISSUE TITLE
Passing component to jdbc functions as db-spec

### ISSUE THREAD

**Issue by xeqi** [weavejester/duct-hikaricp-component#3]
It would be nice to be able to pass the hikaricp component directly to jdbc functions as the db-spec. Then other components do not need to know if they are receiving a URI string, a {:connection ..} map, or some other db-spec vs a hikaricp component.  This is particularly useful for setting up test cases where starting a full connection pool is unnecessary.

My current work around is to use an adapter component. It stores the datastore in `:datastore` so that it can be destructured by jdbc.

``` clojure
(defrecord CPAdapter [cp datasource]
  component/Lifecycle
  (start [t]
    (if datasource
      t
      (assoc t :datasource (get-in cp [:spec :datasource]))))
  (stop [t]
    (assoc t :datasource nil)))
```

**Comment by weavejester** [comment]
I considered this, but it seemed an "easy" but "complex" solution. Easy because it means that you don't need to pull out the database spec explicitly, but complex because _all_ the keys of the component are passed to the Clojure JDBC functions, rather than just the ones necessary.

This creates the possibility for unforeseen interactions in future if, for example, a key in the component happens to conflict with a key used by the JDBC function. By only passing a map with the specific keys we need, a source of complexity is eliminated.

Also, this component is designed to be used in Duct, which advocates using protocols to interact with components that map to an external service. So in Duct, one might write something like:

``` clojure
(extend-type HikariCP
  UserDatabase
  (authenticate [db email password]
    (jdbc/query (:spec db) ...))
  (find-profile [db email]
    (jdbc/query (:spec db) ...)))
```

This means that the database functions always expect a specific type that satisfies a user-defined protocol. In other words, a plain URL or raw DB spec map is never going to happen.

**Comment by xeqi** [comment]
The passing all keys is a downside.

I am using a duct based app. I had considered extending my `Database` protocol to `HikariCP`. Using a direct extension ends up combining the logic for connection pooling along with the sql strings creation. Unfortunately, I need to be compatible with different sql dialects. 

After further thinking, there are several ways I can get the separation of concerns I want without requiring a change or an adapter. Happy to close this. I had debated making it as it seemed a minor issue originally anyways.

**Comment by weavejester** [comment]
Out of interest, are you using Yesql or a derivative?

**Comment by xeqi** [comment]
Yep, trying out yesql for a bit.  I like the ideas behind it, let sql be sql, etc. I know having multiple sql database targets violates the https://github.com/krisajenkins/yesql#when-should-i-not-use-yesql guidelines. Luckily my queries are on the simpler side.

**Comment by skottk** [comment]
Doesn't clojure.jdbc take care of the hiding for you? You pass it a :connection, and it finds a :datasource or a :uri or a set of parameters behind the scenes.
Source: http://clojure-doc.org/articles/ecosystem/java_jdbc/home.html

Seems to work just fine with yesql.

**Comment by skottk** [comment]
More specifically - {:connection {:datasource ....
or {:connection { :classname...
or {:connection { :jdbc-uri..
and so on.

**Comment by xeqi** [comment]
@skottk 

> Doesn't clojure.jdbc take care of the hiding for you?

Yes, if you contain the keys desired in the db-spec. I was making a suggestion that `HikariCP` could change it's internal data mapping to do so. Then users of a `HikariCP` component would not need to know they have a `HikariCP` component, and that they need to reach into `:spec` to find the `db-spec`. They could simply use the component itself as `db-spec`.  (_Note users as a code sense. Could be the functions extending a protocol or another component that ends up with a `HikariCP` component injected into it._)

This suggestion was rejected as jdbc would destructure and use every key in a `HikariCP` component, not just the one for `:datasource`, a fair concern.
